mongo:
  admin:
    url: "mongodb+srv://admin:hgT0qLpFobttAYFO@cluster0.b2b5a.mongodb.net/myFirstDatabase?retryWrites=true&w=majority&ssl=true&ssl_cert_reqs=CERT_NONE"
    usernamme: "admin"
    password: "hgT0qLpFobttAYFO"
  read_only:
    url: "mongodb+srv://read_only:uh1y3xgh56a9Hhyl@cluster0.b2b5a.mongodb.net/myFirstDatabase?retryWrites=true&w=majority&ssl=true&ssl_cert_reqs=CERT_NONE"
    username: "read_only"
    password: "uh1y3xgh56a9Hhyl"
  read_and_write:
    url: "mongodb+srv://read_and_write:Lb8bW2naCU2jfSuP@cluster0.b2b5a.mongodb.net/myFirstDatabase?retryWrites=true&w=majority&ssl=true&ssl_cert_reqs=CERT_NONE"
    username: "read_and_write"
    password: "Lb8bW2naCU2jfSuP"
  clever-cloud:
    url: "mongodb://utbbiucoymjvkdcvtwo0:YI57EmNUFDmChSyS2vX@bmcgn4pwhq1ritg85krm-mongodb.services.clever-cloud.com:2316/bmcgn4pwhq1ritg85krm"
    username: "utbbiucoymjvkdcvtwo0"
    password: "YI57EmNUFDmChSyS2vX"
    port: "2316"
    db: "bmcgn4pwhq1ritg85krm"
    
postgre:
  admin:
    host: "bfzs3f1hetgaveiesq4e-postgresql.services.clever-cloud.com"
    database: "bfzs3f1hetgaveiesq4e"
    user: "u3avr14nzuosnobvncuw"
    password: "72m59WA46DAQkK1iwZDS"
    port: "5484"
    url: "postgresql://u3avr14nzuosnobvncuw:72m59WA46DAQkK1iwZDS@bfzs3f1hetgaveiesq4e-postgresql.services.clever-cloud.com:5484/bfzs3f1hetgaveiesq4e"

  airflow:
    host: "bewz0f98dznsrhnyaxjs-postgresql.services.clever-cloud.com"
    database: "bewz0f98dznsrhnyaxjs"
    user: "ua2iirwnucawdrn13qwq"
    password: "2IYisO1rP08jywXa9Kmr"
    port: "5725"
    url: "postgresql://ua2iirwnucawdrn13qwq:2IYisO1rP08jywXa9Kmr@hv-par5-009.clvrcld.net:12645/bewz0f98dznsrhnyaxjs"

redis:
  admin:
    host: "b6gntx0yefmzkgeeo93o-redis.services.clever-cloud.com"
    password: "meQYqQ7tWr56oZkFAgz"
    port: "3482"
    url: "redis://:meQYqQ7tWr56oZkFAgz@b6gntx0yefmzkgeeo93o-redis.services.clever-cloud.com:3482"