mongo:
  admin:
    url:
    usernamme:
    password:
  read_only:
    url:
    username:
    password:
  read_and_write:
    url:
    username:
    password:

postgre:
  admin:
    host:
    database:
    user:
    password:
    port:
    url:

  localhost:
    host: localhost
    database: test
    user: postgres
    password: postgres
