FROM python:3.8.5-alpine


COPY requirements.txt etl1/requirements.txt
RUN pip install -r etl1/requirements.txt

WORKDIR /etl1
COPY . /etl1

ENTRYPOINT ["python", "main.py", "add_job", "-I", "config.yml"]