FROM python:3.8.5-alpine

WORKDIR /etl1/tools
COPY tools/requirements.txt etl1/requirements.txt
RUN pip install -r etl1/requirements.txt

COPY tools /etl1/tools
COPY data /etl1/tools/data
COPY config /etl1/tools/config

ENTRYPOINT ["python", "main.py", "add_job", "-I", "config.yml"]